POST https://agenda-clin.vercel.app/client
Content-type: application/json

{
    "id": "08504232280",
    "name": "andre",
    "query": "1° Hab."
}

###

GET https://agenda-clin.vercel.app/client
###

GET https://agenda-clin.vercel.app/client?search=08504232280
###

PUT https://agenda-clin.vercel.app/client/08504232280
Content-type: application/json

{
    "name": "andrezinho nerdinho",
    "query": "1° Hab."
}

###

DELETE https://agenda-clin.vercel.app/client/08504232280
